### ISSUE TITLE
this game take too much cpu

### ISSUE THREAD

**Issue by carpetmaker3162** [earthtraveller1/tetris-cli#1]
i tried playing this game but my computer become fried

**Comment by earthtraveller1** [comment]
Oh interesting. Can you describe what exactly is happening?

**Comment by carpetmaker3162** [comment]
i ran cargo run and then my computer be fried rice

**Comment by earthtraveller1** [comment]
Which branch did you clone? There were two branches, if I remember
correctly.

**Comment by carpetmaker3162** [comment]
mater

**Comment by earthtraveller1** [comment]
Wait, but master is just a Hello World program.

**Comment by carpetmaker3162** [comment]
sorry, I once again forgot to add <sarcasm> tags to denote sarcasm

**Comment by earthtraveller1** [comment]
Okay, I will edit my previous messages to account for that.

**Comment by earthtraveller1** [comment]
I am now closing this issue after it not receiving any activity for almost two months, and also because of the fact that it is a joke issue.
